# Generated by Django 4.2 on 2026-05-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_add_notas_to_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='razon_cancelacion',
            field=models.TextField(blank=True, help_text='Razón de la cancelación'),
        ),
    ]
